### ISSUE TITLE
Incorrect example on api reference page

### ISSUE THREAD

**Issue by xkem** [alaress/schoolbox-api-docs#103]
The example reponse at https://api.schoolbox.com.au/#get-/api/assessment/-id- shows participants being returned as an object.
It should be an array, as per schema at https://github.com/alaress/schoolbox-api-docs/blob/develop/openapi/components/schemas/assessment-item.yaml

**Comment by xkem** [comment]
Also, hello :)

**Comment by armatronic** [comment]
Hi xkem :wave: 

This will actually be fixed as part of the next Schoolbox release: we'll rebuild the API docs as part of that process.

**Comment by armatronic** [comment]
We've rebuilt the docs now: participants are now correctly defined as an array of objects.
