### ISSUE TITLE
/api/user/{id} Endpoint Peculiar Behaviour

### ISSUE THREAD

**Issue by Brahmah** [alaress/schoolbox-api-docs#113]
The groups schema for the /api/user/{id} endpoint stipulates that the groups property value is a dictionary with the group’s Id as the key and group obj as the value. This is true for the most part alas, not when the user is not enrolled in any groups.

If the user is enrolled in groups, the response looks like this:

```
{
	“groups”:  {
		“5213”: {...}
	}
}
```

If the user is not enrolled in any groups, it looks like:

```
{
	“groups”:  []
}
```

**Comment by Brahmah** [comment]
@armatronic

**Comment by armatronic** [comment]
@Brahmah we'll be fixing this in the next two weeks: however, it won't be released until the next major Schoolbox release.

For what it's worth `groups` should be an array instead of an object: we'll fix that and update the docs to match.

**Comment by Brahmah** [comment]
Thanks, @armatronic!

Related: #86

**Comment by Brahmah** [comment]
Fixed, Thanks @tomcdonnell
