### ISSUE TITLE
Inaccurate Documentation

### ISSUE THREAD

**Issue by Brahmah** [alaress/schoolbox-api-docs#21]
Hi there,

Only a POST request appears to work for the following endpoint; It's documented as requiring the GET method.

https://api.schoolbox.com.au/#operation/commsNewsSaveForLater.postAdd

**Comment by armatronic** [comment]
Thank you for your report @Brahmah: this definitely looks like an issue with our documentation.

I'll raise a ticket to get it changed.

**Comment by armatronic** [comment]
Hi @Brahmah : the documentation should now be updated.

We have switched to a new API documentation system: the new link is http://api.schoolbox.com.au/#post-/news/saved/-id-/add

**Comment by Brahmah** [comment]
Thank you for your swift response!

The new docs are pretty nice, great work!
